apiVersion: v1
kind: Service
metadata:
  name: piedotbot-redis
  labels:
    app.kubernetes.io/name: piedotbot
    app.kubernetes.io/component: redis
    app.kubernetes.io/part-of: piedotbot
spec:
  ports:
    - port: 6379
      protocol: TCP
  selector:
    app.kubernetes.io/name: piedotbot
    app.kubernetes.io/component: redis
    app.kubernetes.io/part-of: piedotbot
  type: ClusterIP
  clusterIP: None
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: piedotbot-redis
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: piedotbot
      app.kubernetes.io/component: redis
      app.kubernetes.io/part-of: piedotbot
  serviceName: "redis"
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: piedotbot
        app.kubernetes.io/component: redis
        app.kubernetes.io/part-of: piedotbot
    spec:
      containers:
        - name: redis
          image: redis:6.0-alpine
          args:
            - "/srv/cfg/redis.conf"
          ports:
            - containerPort: 6379
              name: web
          volumeMounts:
            - name: redis-aof
              mountPath: /data
            - name: redis-config
              mountPath: /srv/cfg
          resources:
            requests:
              cpu: 1m
              memory: 10Mi
            limits:
              cpu: 50m
              memory: 50Mi
      volumes:
        - name: redis-config
          configMap:
            name: piedotbot-redis-config
  volumeClaimTemplates:
    - metadata:
        name: redis-aof
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: slow
        resources:
          requests:
            storage: 50Mi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: piedotbot-redis-config
data:
  redis.conf: |
    maxmemory 40mb
    maxmemory-policy volatile-ttl
