name: Deploy main branch to production

on:
  push:
    branches:
      - main

jobs:
  push:
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write

    uses: ./.github/workflows/_docker.yml
    with:
      registry: ${{ vars.REGISTRY }}
      registry_namespace: ${{ vars.REGISTRY_NAMESPACE }}
      image_name: ${{ vars.IMAGE_NAME }}
      push: true

  deploy:
    needs: push

    uses: ./.github/workflows/_deploy.yml
    with:
      registry: ${{ vars.REGISTRY }}
      registry_namespace: ${{ vars.REGISTRY_NAMESPACE }}
      image_name: ${{ vars.IMAGE_NAME }}
      environment: production
