name: Deploy main branch to $ENVIRONMENT
run-name: Deploy main to $ENVIRONMENT

on:
  push:
    branches:
      - main

env:
  ENVIRONMENT: production

jobs:
  push:
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write

    uses: ./.github/workflows/_docker.yml
    with:
      registry: ${{ vars.REGISTRY }}
      registry_namespace: ${{ vars.REGISTRY_NAMESPACE }}
      image_name: ${{ vars.IMAGE_NAME }}
      push: true

  deploy:
    needs: push

    uses: ./.github/workflows/_deploy.yml
    with:
      registry: ${{ vars.REGISTRY }}
      registry_namespace: ${{ vars.REGISTRY_NAMESPACE }}
      image_name: ${{ vars.IMAGE_NAME }}
      environment: $ENVIRONMENT
