name: Build and Test

on:
  pull_request:

jobs:
  test:
    uses: ./.github/workflows/_docker.yml
    with:
      registry: ${{ vars.REGISTRY }}
      registry_namespace: ${{ vars.REGISTRY_NAMESPACE }}
      image_name: ${{ vars.IMAGE_NAME }}
      push: false
